//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_cafeteria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulos()
        {
            this.CAFETERIARTICULO = new HashSet<CAFETERIARTICULO>();
            this.DetalleFactura = new HashSet<DetalleFactura>();
            this.FACTURACION_ARTICULOS = new HashSet<FACTURACION_ARTICULOS>();
        }
    
        public int ID { get; set; }

        [RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Solo letras permitidas!")]
        [Display(Name = "Descripcion"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public string DESCRIPCION { get; set; }

        [Display(Name = "Marca"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public Nullable<int> IDMARCA { get; set; }

        [Display(Name = "Proveedor"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public Nullable<int> IDPROVEEDOR { get; set; }

        [Display(Name = "Costo"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public decimal COSTO { get; set; }

        [RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Solo letras permitidas!")]
        [Display(Name = "Existencia"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public int EXISTENCIA { get; set; }

        [Display(Name = "Estado"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public Nullable<int> Estado { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAFETERIARTICULO> CAFETERIARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURACION_ARTICULOS> FACTURACION_ARTICULOS { get; set; }
        public virtual ESTADO ESTADO1 { get; set; }
    }
}
