//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_cafeteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAFETERIARTICULO
    {
        public int ID { get; set; }
        public Nullable<int> IDARTICULO { get; set; }
        public Nullable<int> IDCAFETERIA { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual CAFETERIA CAFETERIA { get; set; }
    }
}
