//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_cafeteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int idDetalleFactura { get; set; }
        public Nullable<int> idArticulo { get; set; }
        public Nullable<int> idFactura { get; set; }
        public Nullable<int> unidades { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
