//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_cafeteria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CafeteriaUnapecEntities : DbContext
    {
        public CafeteriaUnapecEntities()
            : base("name=CafeteriaUnapecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulos> Articulos { get; set; }
        public virtual DbSet<CAFETERIA> CAFETERIA { get; set; }
        public virtual DbSet<CAFETERIAEMPLEADO> CAFETERIAEMPLEADO { get; set; }
        public virtual DbSet<CAFETERIARTICULO> CAFETERIARTICULO { get; set; }
        public virtual DbSet<CAMPUS> CAMPUS { get; set; }
        public virtual DbSet<DetalleFactura> DetalleFactura { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<FACTURACION_ARTICULOS> FACTURACION_ARTICULOS { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<TIPOUSUARIO> TIPOUSUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<TANDALABOR> TANDALABOR { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
