//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_cafeteria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.Articulos = new HashSet<Articulos>();
        }
    
        public int ID { get; set; }

        [Display(Name = "Proveedor"), Required(ErrorMessage = "Es obligatorio")]
        public string NOMBRE { get; set; }

        [Display(Name = "RNC"), Required(ErrorMessage = "Es obligatorio")]
        [StringLength(9, MinimumLength = 9, ErrorMessage = "La longitud del RNC es incorrecta.")]
        public string RNC { get; set; }

        [Display(Name = "Fecha de Registro"), Required(ErrorMessage = "Es obligatorio.")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public Nullable<int> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulos> Articulos { get; set; }
        public virtual ESTADO ESTADO1 { get; set; }
    }
}
