//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_cafeteria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.Factura = new HashSet<Factura>();
            this.FACTURACION_ARTICULOS = new HashSet<FACTURACION_ARTICULOS>();
        }
    
        public int ID { get; set; }

        [RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Solo letras permitidas!")]
        [Display(Name = "Nombre"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public string NOMBRE { get; set; }

        [StringLength(11, ErrorMessage = "La longitud es incorrecta", MinimumLength = 11)]
        [Display(Name = "Cedula"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public string CEDULA { get; set; }

        [Display(Name = "Tipo de Usuario"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public Nullable<int> IDTIPOUSUARIO { get; set; }
        
        [Display(Name = "Limite de Credito"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public Nullable<decimal> LIMITECREDITO { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Registro"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }

        [Display(Name = "Estado"), Required(ErrorMessage = "El nombre del ítem es obligatorio")]
        public Nullable<int> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURACION_ARTICULOS> FACTURACION_ARTICULOS { get; set; }
        public virtual TIPOUSUARIO TIPOUSUARIO { get; set; }
        public virtual ESTADO ESTADO1 { get; set; }
    }
}
