//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCafeteriaUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura_View
    {
        public Nullable<int> UNIDADES { get; set; }
        public int IDFACTURA { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal COSTO { get; set; }
    }
}
