//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCafeteriaUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURACION_ARTICULOS
    {
        public int NoFactura { get; set; }
        public int Unidades { get; set; }
        public int IdEmpleado { get; set; }
        public int IdArticulo { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public decimal MontoArticulo { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
