//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCafeteriaUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURACIONARTICULO
    {
        public int ID { get; set; }
        public Nullable<int> IDEMPLEADO { get; set; }
        public Nullable<int> IDARTICULO { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public decimal MONTO { get; set; }
        public int UNIDADVENDIDA { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
    }
}
