//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCafeteriaUnapec
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAFETERIAUNAPECEntities : DbContext
    {
        public CAFETERIAUNAPECEntities()
            : base("name=CAFETERIAUNAPECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CAFETERIA> CAFETERIA { get; set; }
        public virtual DbSet<CAFETERIARTICULO> CAFETERIARTICULO { get; set; }
        public virtual DbSet<CAMPUS> CAMPUS { get; set; }
        public virtual DbSet<detallefactura> detallefactura { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<FACTURACION_ARTICULOS> FACTURACION_ARTICULOS { get; set; }
        public virtual DbSet<FACTURACIONARTICULO> FACTURACIONARTICULO { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<TANDALABOR> TANDALABOR { get; set; }
        public virtual DbSet<TIPOUSUARIO> TIPOUSUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<DetalleFactura_View> DetalleFactura_View { get; set; }
        public virtual DbSet<MontoTotal> MontoTotal { get; set; }
        public virtual DbSet<CAFETERIAEMPLEADO> CAFETERIAEMPLEADO { get; set; }
    }
}
