//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCafeteriaUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string RNC { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public string ESTADO { get; set; }
    }
}
